name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.1', '8.2']
        swoole: ['yes', 'no']
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/actions/ci-setup'
        with:
          php-version: ${{ matrix.php-version }}
          php-extensions: openswoole-22.0.0
          extensions-cache-key: publish-swagger-spec-extensions-${{ matrix.php-version }}
          install-deps: 'no'
      - if: ${{ matrix.swoole == 'yes' }}
        run: ./build.sh ${GITHUB_REF#refs/tags/v}
      - if: ${{ matrix.swoole == 'no' }}
        run: ./build.sh ${GITHUB_REF#refs/tags/v} --no-swoole
      - uses: actions/upload-artifact@v3
        with:
          name: dist-files-${{ matrix.php-version }}-${{ matrix.swoole }}
          path: build

  publish:
    needs: ['build']
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: build
      - name: Publish release with assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            build/*/shlink*_dist.zip

  delete-artifacts:
    needs: ['publish']
    runs-on: ubuntu-22.04
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: dist-files-*
